name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Test pre-commit hooks
        uses: pre-commit/action@v3.0.0

  tests-bash:
    needs: pre-commit
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up the environment
        run: |
          ./environment_setup.sh
      - name: Run tests with Slurm
        run: |
          srun \
            --account $VILA_SLURM_ACCOUNT \
            --partition $VILA_SLURM_PARTITION \
            --job-name $VILA_SLURM_ACCOUNT:ci/tests-bash \
            --nodes 1 \
            --gpus-per-node 8 \
            --time 1:00:00 \
              bash -c "for t in tests/bash/test_*.sh; do echo \$t; bash \$t; done"

  tests-python:
    needs: pre-commit
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up the environment
        run: |
          ./environment_setup.sh
      - name: Run tests with Slurm
        run: |
          srun \
            --account $VILA_SLURM_ACCOUNT \
            --partition $VILA_SLURM_PARTITION \
            --job-name $VILA_SLURM_ACCOUNT:ci/tests-python \
            --nodes 1 \
            --gpus-per-node 8 \
            --time 1:00:00 \
              pytest tests/python
