name: tests-python

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-python:
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up the environment
        run: |
          ./environment_setup.sh
      - name: Run tests with Slurm
        run: |
          srun \
            --account $VILA_SLURM_ACCOUNT \
            --partition $VILA_SLURM_PARTITION \
            --job-name $VILA_SLURM_ACCOUNT:ci/tests-python \
            --nodes 1 \
            --gpus-per-node 8 \
            --time 1:00:00 \
              pytest tests/python
