name: Unit Tests
on: [pull_request, ]

# run only one unit test for a branch / tag.
concurrency:
  group: ci-unit_test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          # change to a single installation bash.
          pip install black
          bash environment_setup.sh 

      - name: Run tests
        run: |
          #TODO(ligeng): switch to pytest
          # for f in tests/*.py; do
          #     python $f
          # done
          for pyfile in $(find ./tests/ -iname "*.py" -not -path "./tests/gpu_tests/*" -not -path "./tests/archive_tests/*" | xargs); do
              python $f
          done 

